matrix:
  include:
    - language: rust
      cache: cargo
      addons:
        apt:
          packages:
            - libssl-dev
      before_cache: |
        if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
            cargo install cargo-tarpaulin -f
        fi
      before_script:
        - rustup component add clippy --toolchain stable
      script:
        - cargo build --verbose --all
        - cargo test --verbose --all
        - cargo clippy --verbose --all
      after_success: |
        if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
            cargo tarpaulin --all --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
        fi
