name: Rust

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install latest stable
                uses: actions-rs/toolchain@v1
                with:
                    toolchain: stable
                    override: true
            - uses: actions/checkout@v1
            - name: Check Version
              run: cargo --version --verbose
            - name: Build
              run: cargo build --verbose
            - name: Run tests
              run: cargo test --verbose
